---
# system packages
- name: install packages
  apt: pkg={{item}} state=latest
  with_items:
  - nginx

# nginx setup
- name: copy nginx conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
- name: make sure nginx is running
  service: name=nginx state=started enabled=yes