---
- name: map live domain to localhost on server
  lineinfile: dest=/etc/hosts regexp="^127\.0\.0\.1.*\# application" line="127.0.0.1 {{domains | join(' ')}} \# application" state=present

# setup git key
- name: copy in git private key to root
  copy: src={{farcry_key}} dest=/opt/project.pem mode=0600
  when: farcry_key != ""
- name: key path
  set_fact: 
    local_key_path: "/opt/project.pem"
    remote_key_path: "{{farcry_key}}"
  when: farcry_key != ""
- name: secure local key file
  file: path={{farcry_key}} mode=0600
  delegate_to: 127.0.0.1
  sudo: False
  when: farcry_key != ""

# check out project using script
- name: get shallow local copy of project repo
  git: repo={{farcry_repository}} version={{farcry_branch}} dest=/tmp/{{farcry_repository|basename}} key_file={{local_key_path}} accept_hostkey=True
  delegate_to: 127.0.0.1
  sudo: False
  run_once: true
- name: update checkouts
  git: repo={{item.repo}} version={{item.version}} dest=/opt/www/{{item.path}} key_file={{remote_key_path}} accept_hostkey=True force={{farcry_fcscript_overridechanges}}
  with_fcdeploy:
  - /tmp/{{farcry_repository|basename}}/{{farcry_fcscript}}
  ignore_errors: True
  notify: restart Railo

# setup nginx settings
- name: update certificate variables (self-signed)
  set_fact: 
    nginx_certificate: "/etc/nginx/ssl/site.crt"
    nginx_certificate_key: "/etc/nginx/ssl/site.key"
  when: nginx_selfsigned == True
- name: copy website conf
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/default
  notify: restart nginx
- name: create ssl directory
  file: path=/etc/nginx/ssl state=directory
  when: nginx_selfsigned == True
- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=AU/ST=NSW/L=Sydney/O=Daemon/CN={{ domains[0] }}" -days 3650 -keyout {{nginx_certificate_key}} -out {{nginx_certificate}} -extensions v3_ca creates={{nginx_certificate}}
  when: nginx_selfsigned == True
  notify: restart nginx
- meta: flush_handlers

# setup cfml engine settings
- name: ping site to create WEB-INF
  shell: "curl --header 'Host: {{domains[0]}}' 'http://127.0.0.1/'"
  args:
    creates: /opt/WEB-INF
- name: update railo-web.xml.cfm
  template: src=railo-web.xml.cfm dest=/opt/WEB-INF/railo-web.xml.cfm mode=0660
  when: role_railo is not defined or role_railo
  notify: restart Railo
- name: update lucee-web.xml.cfm
  template: src=lucee-web.xml.cfm dest=/opt/WEB-INF/lucee-web.xml.cfm mode=0660
  when: role_lucee is not defined or role_lucee
  notify: restart lucee
- meta: flush_handlers
- name: sync railo logs
  cron: name="railo log sync" job="for f in `ls /opt/WEB-INF/logs/`; do cp /opt/WEB-INF/logs/$f {{log_sync_directory}}/railo-$f; done"
  when: log_sync_directory != ""

# run farcry installer
- name: check if database is set up (railo)
  command: mysql --host={{cfml_datasource_host}} --port={{cfml_datasource_port}} --user={{cfml_datasource_username}} --password='{{cfml_datasource_password}}' -e 'SELECT distinct(locale) as locale from dmProfile' {{cfml_datasource_database}}
  register: db_check
  ignore_errors: yes
  when: farcry_installer_run and role_railo is not defined or role_railo
- name: install project data
  shell: "curl 'http://localhost/webtop/install/' -H 'Host: {{domains[0]}}' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: http://{{domains[0]}}/webtop/install/' -H 'Connection: keep-alive' -H 'Content-Type: application/x-www-form-urlencoded' --data 'selectedSkeleton=&displayName={{farcry_installer_displayname}}&projectDirectoryName={{farcry_installer_project}}&name={{farcry_installer_project}}&updateappKey={{farcry_installer_updateappkey}}&dsn={{cfml_datasource}}&dbType={{cfml_datasource_type}}&dbOwner=&farcryUserPassword={{farcry_installer_password}}&installAction=install'"
  when: farcry_installer_run and db_check|failed
- name: project updateall
  shell: "curl 'http://localhost/?updateall={{farcry_installer_updateappkey}}' -H 'Host: {{domains[0]}}' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: http://{{domains[0]}}/' -H 'Connection: keep-alive'"
  when: farcry_installer_run and db_check|failed